# 手写Promise
  1. Promise 就是一个类 在执行这个类的时候 需要传递一个执行器进去 执行器会立即执行
  2. Promise 中有三种状态 分别为 成功 fulfilled 失败 rejected 等待 pending
    pending -> fulfilled
    pending -> rejected
    一旦状态确定就不可更改
  3. resolve和reject函数是用来更改状态的
    resolve: fulfilled
    reject: rejected
  4. then方法内部做的事情就判断状态 如果状态是成功 调用成功的回调函数 如果状态是失败 调用失败回调函数 then方法是被定义在原型对象中的
  5. then成功回调有一个参数 表示成功之后的值 then失败回调有一个参数 表示失败后的原因
  6. 同一个promise对象下面的then方法是可以被调用多次的
  7. then方法是可以被链式调用的, 后面then方法的回调函数拿到值的是上一个then方法的回调函数的返回值
## 核心逻辑实现
核心逻辑，可以如下实现
```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'reject'

class MyPromise {
    status = PENDING
    value = undefined
    reason = undefined
    constructor(fn) {
        fn(this.resolve, this.reject)
    }
    resolve = (value) => {
        if (this.status == FULFILLED) return
        if (this.status == PENDING) {
            this.status = FULFILLED
            this.value = value
        }
    }
    reject = (reason) => {
        if (this.status == REJECTED) return
        if (this.status == PENDING) {
            this.status = REJECTED
            this.reason = reason
        }
    }
    then(successCallback, failCallback) {
        if (this.status == FULFILLED) {
            successCallback(this.value)
        } else if (this.status == REJECTED) {
            failCallback(this.reason)
        }
    }
}

const a = new MyPromise((resolve, reject) => {
    resolve(2)
})
a.then((value) => {
    console.log('value', value)
}, (reason) => {
    console.log('reason', reason)
})
```
## 加入异步逻辑
考虑异步情况，思路：把`successCallback, failCallback`存储起来，然后修改resolve和reject方法，`this.successCallback && this.successCallback(this.value)`，执行成功和失败的回调。
```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'reject'

class MyPromise {
    status = PENDING
    value = undefined
    reason = undefined
    successCallback = undefined //成功回调，处理异步逻辑用的
    failCallback = undefined  // 失败回调，处理异步逻辑用的
    constructor(fn) {
        fn(this.resolve, this.reject)
    }
    resolve = (value) => {
        if (this.status == FULFILLED) return
        if (this.status == PENDING) {
            this.status = FULFILLED
            this.value = value
        }
        // 处理异步：判断成功回调是否存在，存在则调用
        this.successCallback && this.successCallback(this.value)
    }
    reject = (reason) => {
        if (this.status == REJECTED) return
        if (this.status == PENDING) {
            this.status = REJECTED
            this.reason = reason
        }
        // 处理异步：判断失败回调是否存在，存在则调用
        this.failCallback && this.failCallback(this.reason)
    }
    then(successCallback, failCallback) {
        if (this.status == FULFILLED) {
            successCallback(this.value)
        } else if (this.status == REJECTED) {
            failCallback(this.reason)
        } else {
            // 当前的状态是等待，这里处理异步的情况，但是不知道状态啥时候改变怎么办，方法是利用回调函数
            // 处理异步：把成功和失败的回调保存起来
            this.successCallback = successCallback
            this.failCallback = failCallback
        }
    }
}

const a = new MyPromise((resolve, reject) => {
    setTimeout(() => {
        resolve(2)
    }, 2000)
})
a.then((value) => {
    console.log('value', value)
}, (reason) => {
    console.log('reason', reason)
})
```
## 实现then方法多次调用
实现多次调用then方法。思路：添加多个处理函数，把`successCallback, failCallback`用数组保存起来。
```js
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'reject'

class MyPromise {
    status = PENDING
    value = undefined
    reason = undefined
    successCallback = [] // 支持多次调用then：改成数组的形式
    failCallback = []  // 支持多次调用then：改成数组的形式
    constructor(fn) {
        fn(this.resolve, this.reject)
    }
    resolve = (value) => {
        if (this.status == FULFILLED) return
        if (this.status == PENDING) {
            this.status = FULFILLED
            this.value = value
        }
        // 支持多次调用then
        // this.successCallback && this.successCallback(this.value)
        while (this.successCallback.length) this.successCallback.shift()(this.value)
    }
    reject = (reason) => {
        if (this.status == REJECTED) return
        if (this.status == PENDING) {
            this.status = REJECTED
            this.reason = reason
        }
        // 支持多次调用then
        // this.failCallback && this.failCallback(this.reason)
        while (this.failCallback.length) this.failCallback.shift()(this.reason)
    }
    then(successCallback, failCallback) {
        if (this.status == FULFILLED) {
            successCallback(this.value)
        } else if (this.status == REJECTED) {
            failCallback(this.reason)
        } else {
            // 当前的状态是等待，这里处理异步的情况，但是不知道状态啥时候改变怎么办，方法是利用回调函数
            // 支持多次调用then：把成功和失败的回调加到事件队列里
            this.successCallback.push(successCallback)
            this.failCallback.push(failCallback)
        }
    }
}

const a = new MyPromise((resolve, reject) => {
    setTimeout(() => {
        resolve(2)
    }, 2000)
})
a.then((value) => {
    console.log('value', value)
})
a.then((value) => {
    console.log('value', value)
})
a.then((value) => {
    console.log('value', value)
})
```
## 实现then方法链式调用
思路：
1. 实现链式调用，在then里返回新的promise，为什么要新的，因为原来的promise状态变了，不能再更改了
2. 如何让上一个then方法的返回值传递给下一个then方法的回调函数？取到前一个then的结果，传给下一个then
3. then方法不能返回自身。需要判断promise2和x是否相等
```js

then(successCallback, failCallback) {
    let promise2 = new MyPromise((resovle, reject) => {
        // 同步情况
        if (this.status == FULFILLED) {
            // 这里为什么要setTimeout？因为下面用到了promise2，需要异步方式才能获取到promise2
            setTimeout(() => {
                let x = successCallback(this.value) // 前一个then的结果
                // 判断 x 的值是普通值还是promise对象
                // 如果是普通值 直接调用resolve 
                // 如果是promise对象 查看promsie对象返回的结果 
                // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
                resolvePromise(promise2, x, resovle, reject)
            }, 0) 
        } else if (this.status == REJECTED) {
            // 同步情况
            failCallback(this.reason)
        } else {
            // 这里处理异步的情况，当前的状态是等待，但是不知道状态啥时候改变怎么办，方法是利用回调函数
            // 支持多次调用then：把成功和失败的回调加到事件队列里
            this.successCallback.push(successCallback)
            this.failCallback.push(failCallback)
        }
    })
    return promise2;
}

function resolvePromise(promise2, x, resolve, reject) {
    if (promise2 === x) {
        return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
    }
    if (x instanceof MyPromise) {
        // promise 对象
        // x.then(value => resolve(value), reason => reject(reason));
        x.then(resolve, reject);
    } else {
        // 普通值
        resolve(x);
    }
}

const a = new MyPromise((resolve, reject) => {
    resolve(100)
}).then((value) => {
    return new MyPromise((resovle, reject) => {
        resovle(12)
    })
}).then((value) => {
    console.log('value', value)
    return 300
})
```
## then方法参数可选
思路：不传参数的时候，自己补参数
```js
 then (successCallback, failCallback) {
    // 参数可选
    successCallback = successCallback ? successCallback : value => value;
    // 参数可选
    failCallback = failCallback ? failCallback: reason => { throw reason };
    let promsie2 = new MyPromise((resolve, reject) => {
      // 判断状态
      if (this.status === FULFILLED) {
        setTimeout(() => {
          try {
            let x = successCallback(this.value);
            // 判断 x 的值是普通值还是promise对象
            // 如果是普通值 直接调用resolve 
            // 如果是promise对象 查看promsie对象返回的结果 
            // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
            resolvePromise(promsie2, x, resolve, reject)
          }catch (e) {
            reject(e);
          }
        }, 0)
      }else if (this.status === REJECTED) {
        setTimeout(() => {
          try {
            let x = failCallback(this.reason);
            // 判断 x 的值是普通值还是promise对象
            // 如果是普通值 直接调用resolve 
            // 如果是promise对象 查看promsie对象返回的结果 
            // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
            resolvePromise(promsie2, x, resolve, reject)
          }catch (e) {
            reject(e);
          }
        }, 0)
      } else {
        // 等待
        // 将成功回调和失败回调存储起来
        this.successCallback.push(() => {
          setTimeout(() => {
            try {
              let x = successCallback(this.value);
              // 判断 x 的值是普通值还是promise对象
              // 如果是普通值 直接调用resolve 
              // 如果是promise对象 查看promsie对象返回的结果 
              // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
              resolvePromise(promsie2, x, resolve, reject)
            }catch (e) {
              reject(e);
            }
          }, 0)
        });
        this.failCallback.push(() => {
          setTimeout(() => {
            try {
              let x = failCallback(this.reason);
              // 判断 x 的值是普通值还是promise对象
              // 如果是普通值 直接调用resolve 
              // 如果是promise对象 查看promsie对象返回的结果 
              // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
              resolvePromise(promsie2, x, resolve, reject)
            }catch (e) {
              reject(e);
            }
          }, 0)
        });
      }
    });
    return promsie2;
  }
```
## 实现Promise.all
```js
static all (array) {
  let result = [];
  let index = 0;
  return new MyPromise((resolve, reject) => {
    function addData (key, value) {
      result[key] = value;
      index++;
      if (index === array.length) {
        resolve(result);
      }
    }
    for (let i = 0; i < array.length; i++) {
      let current = array[i];
      if (current instanceof MyPromise) {
        // promise 对象
        current.then(value => addData(i, value), reason => reject(reason))
      }else {
        // 普通值
        addData(i, array[i]);
      }
    }
  })
}
```
## 实现Promise.resolve
```js
static resolve (value) {
  if (value instanceof MyPromise) return value;
  return new MyPromise(resolve => resolve(value));
}
```
## 实现finally
```js
finally (callback) {
  return this.then(value => {
    return MyPromise.resolve(callback()).then(() => value);
  }, reason => {
    return MyPromise.resolve(callback()).then(() => { throw reason })
  })
}
```
## 实现catch
```js
catch (failCallback) {
  return this.then(undefined, failCallback)
}
```
## 完整版promise
```js
const PENDING = 'pending'; // 等待
const FULFILLED = 'fulfilled'; // 成功
const REJECTED = 'rejected'; // 失败

class MyPromise {
  constructor (executor) {
    try {
      executor(this.resolve, this.reject)
    } catch (e) {
      this.reject(e);
    }
  }
  // promsie 状态 
  status = PENDING;
  // 成功之后的值
  value = undefined;
  // 失败后的原因
  reason = undefined;
  // 成功回调
  successCallback = [];
  // 失败回调
  failCallback = [];

  resolve = value => {
    // 如果状态不是等待 阻止程序向下执行
    if (this.status !== PENDING) return;
    // 将状态更改为成功
    this.status = FULFILLED;
    // 保存成功之后的值
    this.value = value;
    // 判断成功回调是否存在 如果存在 调用
    // this.successCallback && this.successCallback(this.value);
    while(this.successCallback.length) this.successCallback.shift()()
  }
  reject = reason => {
    // 如果状态不是等待 阻止程序向下执行
    if (this.status !== PENDING) return;
    // 将状态更改为失败
    this.status = REJECTED;
    // 保存失败后的原因
    this.reason = reason;
    // 判断失败回调是否存在 如果存在 调用
    // this.failCallback && this.failCallback(this.reason);
    while(this.failCallback.length) this.failCallback.shift()()
  }
  then (successCallback, failCallback) {
    // 参数可选
    successCallback = successCallback ? successCallback : value => value;
    // 参数可选
    failCallback = failCallback ? failCallback: reason => { throw reason };
    let promsie2 = new MyPromise((resolve, reject) => {
      // 判断状态
      if (this.status === FULFILLED) {
        setTimeout(() => {
          try {
            let x = successCallback(this.value);
            // 判断 x 的值是普通值还是promise对象
            // 如果是普通值 直接调用resolve 
            // 如果是promise对象 查看promsie对象返回的结果 
            // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
            resolvePromise(promsie2, x, resolve, reject)
          }catch (e) {
            reject(e);
          }
        }, 0)
      }else if (this.status === REJECTED) {
        setTimeout(() => {
          try {
            let x = failCallback(this.reason);
            // 判断 x 的值是普通值还是promise对象
            // 如果是普通值 直接调用resolve 
            // 如果是promise对象 查看promsie对象返回的结果 
            // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
            resolvePromise(promsie2, x, resolve, reject)
          }catch (e) {
            reject(e);
          }
        }, 0)
      } else {
        // 等待
        // 将成功回调和失败回调存储起来
        this.successCallback.push(() => {
          setTimeout(() => {
            try {
              let x = successCallback(this.value);
              // 判断 x 的值是普通值还是promise对象
              // 如果是普通值 直接调用resolve 
              // 如果是promise对象 查看promsie对象返回的结果 
              // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
              resolvePromise(promsie2, x, resolve, reject)
            }catch (e) {
              reject(e);
            }
          }, 0)
        });
        this.failCallback.push(() => {
          setTimeout(() => {
            try {
              let x = failCallback(this.reason);
              // 判断 x 的值是普通值还是promise对象
              // 如果是普通值 直接调用resolve 
              // 如果是promise对象 查看promsie对象返回的结果 
              // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
              resolvePromise(promsie2, x, resolve, reject)
            }catch (e) {
              reject(e);
            }
          }, 0)
        });
      }
    });
    return promsie2;
  }
  finally (callback) {
    return this.then(value => {
      return MyPromise.resolve(callback()).then(() => value);
    }, reason => {
      return MyPromise.resolve(callback()).then(() => { throw reason })
    })
  }
  catch (failCallback) {
    return this.then(undefined, failCallback)
  }
  static all (array) {
    let result = [];
    let index = 0;
    return new MyPromise((resolve, reject) => {
      function addData (key, value) {
        result[key] = value;
        index++;
        if (index === array.length) {
          resolve(result);
        }
      }
      for (let i = 0; i < array.length; i++) {
        let current = array[i];
        if (current instanceof MyPromise) {
          // promise 对象
          current.then(value => addData(i, value), reason => reject(reason))
        }else {
          // 普通值
          addData(i, array[i]);
        }
      }
    })
  }
  static resolve (value) {
    if (value instanceof MyPromise) return value;
    return new MyPromise(resolve => resolve(value));
  }
}

function resolvePromise (promsie2, x, resolve, reject) {
  if (promsie2 === x) {
    return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
  }
  if (x instanceof MyPromise) {
    // promise 对象
    // x.then(value => resolve(value), reason => reject(reason));
    x.then(resolve, reject);
  } else {
    // 普通值
    resolve(x);
  }
}

module.exports = MyPromise;
```